name: Build and publish image to docker hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api -t bfeeney6/devops-qr-code-api:latest
          docker build ./front-end-nextjs -t bfeeney6/devops-qr-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u bfeeney6 -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push bfeeney6/devops-qr-code-api:latest
          docker push bfeeney6/devops-qr-frontend:latest